# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_memorialGenerator.ui'
#
# Created: Tue Sep 30 09:28:57 2014
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(657, 466)
        self.gridLayout_7 = QtGui.QGridLayout(Dialog)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.frame_5 = QtGui.QFrame(Dialog)
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.gridLayout_5 = QtGui.QGridLayout(self.frame_5)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label = QtGui.QLabel(self.frame_5)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_5.addWidget(self.label)
        self.imovelEdit = QtGui.QLineEdit(self.frame_5)
        self.imovelEdit.setObjectName(_fromUtf8("imovelEdit"))
        self.horizontalLayout_5.addWidget(self.imovelEdit)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_2 = QtGui.QLabel(self.frame_5)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_6.addWidget(self.label_2)
        self.proprietarioEdit = QtGui.QLineEdit(self.frame_5)
        self.proprietarioEdit.setObjectName(_fromUtf8("proprietarioEdit"))
        self.horizontalLayout_6.addWidget(self.proprietarioEdit)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_3 = QtGui.QLabel(self.frame_5)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_7.addWidget(self.label_3)
        self.municipioEdit = QtGui.QLineEdit(self.frame_5)
        self.municipioEdit.setText(_fromUtf8(""))
        self.municipioEdit.setObjectName(_fromUtf8("municipioEdit"))
        self.horizontalLayout_7.addWidget(self.municipioEdit)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_4 = QtGui.QLabel(self.frame_5)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_8.addWidget(self.label_4)
        self.comarcaEdit = QtGui.QLineEdit(self.frame_5)
        self.comarcaEdit.setObjectName(_fromUtf8("comarcaEdit"))
        self.horizontalLayout_8.addWidget(self.comarcaEdit)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.gridLayout_5.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_8 = QtGui.QLabel(self.frame_5)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_10.addWidget(self.label_8)
        self.ufEdit = QtGui.QLineEdit(self.frame_5)
        self.ufEdit.setObjectName(_fromUtf8("ufEdit"))
        self.horizontalLayout_10.addWidget(self.ufEdit)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_9 = QtGui.QLabel(self.frame_5)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_11.addWidget(self.label_9)
        self.codIncraEdit = QtGui.QLineEdit(self.frame_5)
        self.codIncraEdit.setObjectName(_fromUtf8("codIncraEdit"))
        self.horizontalLayout_11.addWidget(self.codIncraEdit)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_10 = QtGui.QLabel(self.frame_5)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_12.addWidget(self.label_10)
        self.matriculaEdit = QtGui.QLineEdit(self.frame_5)
        self.matriculaEdit.setObjectName(_fromUtf8("matriculaEdit"))
        self.horizontalLayout_12.addWidget(self.matriculaEdit)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_20 = QtGui.QLabel(self.frame_5)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_13.addWidget(self.label_20)
        self.cadastroEdit = QtGui.QLineEdit(self.frame_5)
        self.cadastroEdit.setObjectName(_fromUtf8("cadastroEdit"))
        self.horizontalLayout_13.addWidget(self.cadastroEdit)
        self.verticalLayout_5.addLayout(self.horizontalLayout_13)
        self.gridLayout_5.addLayout(self.verticalLayout_5, 0, 1, 1, 1)
        self.gridLayout_7.addWidget(self.frame_5, 0, 0, 1, 2)
        self.frame_2 = QtGui.QFrame(Dialog)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_11 = QtGui.QLabel(self.frame_2)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_14.addWidget(self.label_11)
        self.rbmcOrigemEdit = QtGui.QLineEdit(self.frame_2)
        self.rbmcOrigemEdit.setObjectName(_fromUtf8("rbmcOrigemEdit"))
        self.horizontalLayout_14.addWidget(self.rbmcOrigemEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_12 = QtGui.QLabel(self.frame_2)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_15.addWidget(self.label_12)
        self.rbmcEsteEdit = QtGui.QLineEdit(self.frame_2)
        self.rbmcEsteEdit.setObjectName(_fromUtf8("rbmcEsteEdit"))
        self.horizontalLayout_15.addWidget(self.rbmcEsteEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_13 = QtGui.QLabel(self.frame_2)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_16.addWidget(self.label_13)
        self.rbmcNorteEdit = QtGui.QLineEdit(self.frame_2)
        self.rbmcNorteEdit.setObjectName(_fromUtf8("rbmcNorteEdit"))
        self.horizontalLayout_16.addWidget(self.rbmcNorteEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.label_14 = QtGui.QLabel(self.frame_2)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_17.addWidget(self.label_14)
        self.localRbmcEdit = QtGui.QLineEdit(self.frame_2)
        self.localRbmcEdit.setObjectName(_fromUtf8("localRbmcEdit"))
        self.horizontalLayout_17.addWidget(self.localRbmcEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_17)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.frame_2, 1, 0, 1, 1)
        self.frame = QtGui.QFrame(Dialog)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout = QtGui.QGridLayout(self.frame)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_19 = QtGui.QLabel(self.frame)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout.addWidget(self.label_19)
        self.kappaEdit = QtGui.QLineEdit(self.frame)
        self.kappaEdit.setText(_fromUtf8(""))
        self.kappaEdit.setObjectName(_fromUtf8("kappaEdit"))
        self.horizontalLayout.addWidget(self.kappaEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_6 = QtGui.QLabel(self.frame)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_2.addWidget(self.label_6)
        self.meridianoEdit = QtGui.QLineEdit(self.frame)
        self.meridianoEdit.setObjectName(_fromUtf8("meridianoEdit"))
        self.horizontalLayout_2.addWidget(self.meridianoEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_7 = QtGui.QLabel(self.frame)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_3.addWidget(self.label_7)
        self.convergenciaEdit = QtGui.QLineEdit(self.frame)
        self.convergenciaEdit.setObjectName(_fromUtf8("convergenciaEdit"))
        self.horizontalLayout_3.addWidget(self.convergenciaEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_21 = QtGui.QLabel(self.frame)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_4.addWidget(self.label_21)
        self.projectionEdit = QtGui.QLineEdit(self.frame)
        self.projectionEdit.setText(_fromUtf8(""))
        self.projectionEdit.setObjectName(_fromUtf8("projectionEdit"))
        self.horizontalLayout_4.addWidget(self.projectionEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.label_5 = QtGui.QLabel(self.frame)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_23.addWidget(self.label_5)
        self.datumEdit = QtGui.QLineEdit(self.frame)
        self.datumEdit.setObjectName(_fromUtf8("datumEdit"))
        self.horizontalLayout_23.addWidget(self.datumEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_23)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.frame, 1, 1, 1, 1)
        self.frame_4 = QtGui.QFrame(Dialog)
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.gridLayout_4 = QtGui.QGridLayout(self.frame_4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.label_17 = QtGui.QLabel(self.frame_4)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_20.addWidget(self.label_17)
        self.credenciamentoEdit = QtGui.QLineEdit(self.frame_4)
        self.credenciamentoEdit.setObjectName(_fromUtf8("credenciamentoEdit"))
        self.horizontalLayout_20.addWidget(self.credenciamentoEdit)
        self.verticalLayout_4.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.label_18 = QtGui.QLabel(self.frame_4)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_21.addWidget(self.label_18)
        self.artEdit = QtGui.QLineEdit(self.frame_4)
        self.artEdit.setObjectName(_fromUtf8("artEdit"))
        self.horizontalLayout_21.addWidget(self.artEdit)
        self.verticalLayout_4.addLayout(self.horizontalLayout_21)
        self.gridLayout_4.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.frame_4, 2, 0, 1, 1)
        self.frame_3 = QtGui.QFrame(Dialog)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.frame_3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.label_15 = QtGui.QLabel(self.frame_3)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_18.addWidget(self.label_15)
        self.autorEdit = QtGui.QLineEdit(self.frame_3)
        self.autorEdit.setObjectName(_fromUtf8("autorEdit"))
        self.horizontalLayout_18.addWidget(self.autorEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.label_16 = QtGui.QLabel(self.frame_3)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_19.addWidget(self.label_16)
        self.creaEdit = QtGui.QLineEdit(self.frame_3)
        self.creaEdit.setObjectName(_fromUtf8("creaEdit"))
        self.horizontalLayout_19.addWidget(self.creaEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_19)
        self.gridLayout_3.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.frame_3, 2, 1, 1, 1)
        self.frame_6 = QtGui.QFrame(Dialog)
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.gridLayout_6 = QtGui.QGridLayout(self.frame_6)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.folderButton = QtGui.QPushButton(self.frame_6)
        self.folderButton.setToolTip(_fromUtf8(""))
        self.folderButton.setObjectName(_fromUtf8("folderButton"))
        self.horizontalLayout_22.addWidget(self.folderButton)
        self.folderEdit = QtGui.QLineEdit(self.frame_6)
        self.folderEdit.setObjectName(_fromUtf8("folderEdit"))
        self.horizontalLayout_22.addWidget(self.folderEdit)
        self.gridLayout_6.addLayout(self.horizontalLayout_22, 0, 0, 1, 1)
        self.createButton = QtGui.QPushButton(self.frame_6)
        self.createButton.setObjectName(_fromUtf8("createButton"))
        self.gridLayout_6.addWidget(self.createButton, 1, 0, 1, 1)
        self.gridLayout_7.addWidget(self.frame_6, 3, 0, 1, 2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Configurações dos arquivos", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Nome do Imóvel:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Proprietário:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Município:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Comarca:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "UF:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "Código INCRA:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog", "Matrícula:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("Dialog", "Número de Cadastro:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Dialog", "Estação RBMC de origem:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Dialog", "Coordenada E da RBMC:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Dialog", "Coordenada N da RBMC:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Dialog", "Localização da Estação RBMC:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("Dialog", "Fator Kappa:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Meridiano Central:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "Convergencia Meridiana:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("Dialog", "Sistema  de projeção:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "DATUM:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Dialog", "Código do Credencialmento:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Dialog", "Número ART:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Dialog", "Responsável Técnico:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Dialog", "CREA:", None, QtGui.QApplication.UnicodeUTF8))
        self.folderButton.setText(QtGui.QApplication.translate("Dialog", "Diretório para salvar arquivos:", None, QtGui.QApplication.UnicodeUTF8))
        self.createButton.setText(QtGui.QApplication.translate("Dialog", "Criar arquivos", None, QtGui.QApplication.UnicodeUTF8))

